<?php
if(!isset($conditionerr)){
    if (allowedToOpen(3101,'1rtc')) { $conditionerr=' AND b.BranchNo='.$_SESSION['bnum'];} else { $conditionerr='';}
}

$sql0='CREATE TEMPORARY TABLE `acctg_closing_dailycashsalesfordep` AS SELECT `sm`.`BranchNo` AS `BranchNo`,`sm`.`Date` AS `SaleDate`,sum(`ss`.`Amount`) - ifnull((select sum(`lss`.`Amount`) from `acctg_2salesub` `lss` WHERE `lss`.`DebitAccountID` = 705 and `lss`.`CreditAccountID` = 100 and `lss`.`TxnID` = `sm`.`TxnID`),0) AS `CashSales`,ifnull((select sum(`ds`.`Amount`) from `acctg_2depositsub` `ds` WHERE `ds`.`DepDetails` like "income%" and `ds`.`CreditAccountID` = 100 and str_to_date(substr(`ds`.`DepDetails`,7,15),"%m/%d/%Y") = `sm`.`Date` and `ds`.`BranchNo` = `sm`.`BranchNo` group by `ds`.`BranchNo`,str_to_date(substr(`ds`.`DepDetails`,7,15),"%m/%d/%Y")),0) + ifnull((select sum(`ds`.`Amount`) from `acctg_2depositsub` `ds` where `ds`.`DepDetails` like "sales returns with exchange %" and `ds`.`CreditAccountID` = 100 and str_to_date(right(`ds`.`DepDetails`,8),"%m/%d/%Y") = `sm`.`Date` and `ds`.`BranchNo` = `sm`.`BranchNo` group by `ds`.`BranchNo`,str_to_date(substr(`ds`.`DepDetails`,7,15),"%m/%d/%Y")),0) AS `CashDep` from (`acctg_2salemain` `sm` join `acctg_2salesub` `ss` on(`sm`.`TxnID` = `ss`.`TxnID`)) where `ss`.`DebitAccountID` = 100 group by `sm`.`BranchNo`,`sm`.`Date` union all select `sm`.`BranchNo` AS `BranchNo`,`sm`.`Date` AS `SaleDate`,sum(round(`a`.`Amount`,0)) AS `CashSales`,(select sum(`ds`.`Amount`) from `acctg_2depositsub` `ds` where `ds`.`DepDetails` like "%collection for freight%" and `ds`.`CreditAccountID` = 925 and str_to_date(substr(`ds`.`DepDetails`,24,31),"%m/%d/%Y") = `sm`.`Date` and `ds`.`BranchNo` = `sm`.`BranchNo` group by `ds`.`BranchNo`,str_to_date(substr(`ds`.`DepDetails`,24,31),"%m/%d/%Y")) AS `CashDep` from (`invty_2sale` `sm` join `approvals_2freightclients` `a` on(`sm`.`SaleNo` = convert(`a`.`ForInvoiceNo` using utf8) and `sm`.`BranchNo` = `a`.`BranchNo` and `a`.`PriceFreightInclusive` = 0 and `sm`.`txntype` = `a`.`txntype`)) where `sm`.`PaymentType` = 1 group by `sm`.`BranchNo`,`sm`.`Date`
';
$stmt0=$link->prepare($sql0); $stmt0->execute();
$sqlcheck='SELECT c.`BranchNo`,`Branch`,`SaleDate`,TRUNCATE(`CashSales`,2) as `CashSales`,TRUNCATE(`CashDep`,2) as `CashDep`,TRUNCATE(`CashSales`-ifnull(`CashDep`,0),2) as `Diff` FROM `acctg_closing_dailycashsalesfordep` c JOIN `1branches` b on b.BranchNo=c.BranchNo where ((`CashSales`-ifnull(`CashDep`,0))<-0.05 Or (`CashSales`-ifnull(`CashDep`,0))>0.05) AND `SaleDate`<>CURDATE() '.$conditionerr.' ORDER BY Branch, SaleDate';
// echo $sql;
?>