</center>
<div id="content"><div style="position: relative; left: 20%;  width:80%; ">
        <style>
        ul, ol {  list-style-position: outside;   padding-left: 10em;}
        td { text-align: center; width: 100px;}
</style>
All government processes start with a dat file that is generated by a file using <i>Microsoft Excel</i>.
<br><br>
<h3><font style="color:maroon; " >SSS</font></h3>
<ol>
    <b>HR:</b>
    <li>Create .dat file using SSS EELST-MCL File Writer - for monthly contributions &nbsp; &nbsp 
            (<a href='govt/downloadfile.php?filename=SSS EELST-MCL File Writer V[1].2.0.xls'>Download</a>)</li>
    <li>Create .dat file using  LCL File Creator - for monthly loan payments &nbsp; &nbsp 
            (<a href='govt/downloadfile.php?filename=LCL_File_Creator.xls'>Download</a>)</li>
    <li>Send .dat file/s to accounting personnel</li>
    <br>
    <b>Accounting:</b>
    <li>Upload payment via BPI</li>
    <li>Posting of payment for each employee is automatic if via BPI</li>
</ol>
<br>
<h3><font style="color:maroon; " >PAG-IBIG</font></h3>
<ol>
    <b>HR:</b>
    <li>Create .dat file using Pagibig File Generator - for monthly contributions &nbsp; &nbsp 
            (<a href='govt/downloadfile.php?filename=Pagibig_File_generator_Feb 2013.xls'>Download</a>)</li>
    <li>Create .dat file using STL_File generator - for monthly loan payments &nbsp; &nbsp 
            (<a href='govt/downloadfile.php?filename=STL_Pagibig_File_generator_June 2013.xls'>Download</a>)</li>
    <li>Send .dat file/s to accounting personnel</li>
    <br>
    <b>Accounting:</b>
    <li>Upload payment via BPI</li>
    <li>Posting of payment for each employee is automatic if via BPI</li>
</ol>
<br>
<h3><font style="color:maroon; " >PHILHEALTH</font></h3>
<ol>
    <b>HR:</b>
    <li>Create .dat file using PhilHealthRemittance  Writer &nbsp; &nbsp 
            (<a href='govt/downloadfile.php?filename=PhilHealthRemittance_2014_fin.xls'>Download</a>) </li>
    <li>Send .dat file/s to accounting personnel</li>
    <br>
    <b>Accounting:</b>
    <li>Upload payment via BPI</li>
    <li>Posting of payment for each employee is automatic if via BPI</li>
</ol>
<br><br><br>
		
As of 2019-Nov-30, the following have <font style="color:maroon; " >BPI</font> access

<table>
    <th><td>SSS</td><td>Pag-Ibig</td><td>PhilHealth</td></th>
    <tr><td>1Rotary</td><td>Y</td><td>Y</td><td></td></tr>
    <tr><td>Rotek</td><td>Y</td><td>Y</td><td></td></tr>
    <tr><td>North Rotek</td><td></td><td>Y</td><td>Y</td></tr>
    <tr><td>Reliance</td><td>Y</td><td>Y</td><td>Y</td></tr>
    <tr><td>Panay</td><td>Y</td><td>Y</td><td>Y</td></tr>
    <tr><td>Rodlink</td><td></td><td></td><td></td></tr>
</table>
<center>